In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../data/house_prices.csv')

In [4]:
crim = df['CRIM']
nox = df['NOX']
res = np.inner(crim, nox)
print(res)

1226.1231702310001


In [6]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', 'TAX']]
X_t = np.transpose(X)
cov_x = X_t.dot(X)

In [7]:
cov_x

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [8]:
e, v = np.linalg.eig(cov_x)

In [9]:
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [10]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

In [13]:
v_T = np.transpose(v)

In [14]:
v_T.dot(cov_x).dot(v)

array([[ 1.01109837e+08, -1.25592525e-09, -2.02310183e-09,
         7.42580584e-10, -1.81942141e-08],
       [-2.72675835e-09,  3.74919516e+05,  1.91899897e-11,
        -4.57094862e-11,  1.31811858e-09],
       [-1.77840627e-09,  8.76833138e-12,  2.99553705e+04,
        -4.93424741e-11,  2.22439152e-11],
       [ 7.34772892e-10, -3.89910097e-11, -4.43062342e-11,
         2.40312204e+03, -4.82423279e-11],
       [-1.81896722e-08,  1.31867842e-09,  2.23209591e-11,
        -4.81921207e-11,  2.90022330e+00]])

In [15]:
u, s, vt = np.linalg.svd(cov_x)

In [16]:
u

array([[-1.17248568e-02,  4.34541539e-02,  9.89273583e-01,
        -1.38967257e-01, -3.78876853e-04],
       [-1.21545113e-03, -3.97729110e-03, -5.48368537e-03,
        -3.74537281e-02, -9.99274663e-01],
       [-1.28461807e-02, -4.11504926e-02, -1.37240647e-01,
        -9.88869506e-01,  3.79962757e-02],
       [-1.54544362e-01, -9.86199762e-01,  4.66395497e-02,
         3.66695593e-02,  2.48287726e-03],
       [-9.87832003e-01,  1.54313263e-01, -1.72471505e-02,
         8.81831838e-03,  3.51466736e-04]])

In [17]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [18]:
vt

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [ 4.34541539e-02, -3.97729110e-03, -4.11504926e-02,
        -9.86199762e-01,  1.54313263e-01],
       [ 9.89273583e-01, -5.48368537e-03, -1.37240647e-01,
         4.66395497e-02, -1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])