In [1]:
x = [4, 2, 8, 9, 3]
min_value = min(x)
min_value

2

In [2]:
x.index(min_value)

1

In [4]:
import numpy as np

In [5]:
np.min(x)

2

In [7]:
np.argmin(x)

1

In [8]:
#스칼라
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv('./data/house_prices.csv')

In [10]:
df.head(3)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7

In [11]:
df.iloc[2,4]

0.469

In [12]:
df.iloc[3,5]

6.998

In [14]:
df.iloc[2,3] + df.iloc[4,5]

7.147

In [25]:
A = np.array([1,2,3,4,5,6,7,8, 9, 10, 11, 12, 13,14,15,16])
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [27]:
A1 = A.reshape(16,1)
print(A1)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [28]:
A2 = A1.reshape(-1)
print(A2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [29]:
A3 = A2.reshape(8,-1)
print(A3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [32]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [33]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [34]:
C = np.concatenate((A, B), axis=0)
print(C)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
C.shape

(4, 2)

In [36]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', 'TAX']]

In [37]:
X

CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [38]:
X_t = np.transpose(X)

In [39]:
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [40]:
X_t = X.T

In [41]:
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [42]:
XtX = X_t@X

In [43]:
np.linalg.det(XtX)

7.91431657769047e+21

In [44]:
A = df[['CRIM', 'NOX', 'NOX']]
AtA = A.T@A
AtA

CRIM         NOX         NOX
CRIM  43970.343555  1226.12317  1226.12317
NOX    1226.123170   162.47038   162.47038
NOX    1226.123170   162.47038   162.47038

In [45]:
np.linalg.det(AtA)

-1.6066291246500755e-07

In [46]:
XtX_inv = np.linalg.inv(XtX)

In [47]:
print(XtX_inv)

[[ 4.07613803e-05  1.32526683e-04  4.76832932e-05 -1.01889386e-06
  -1.10744437e-06]
 [ 1.32526683e-04  3.44301609e-01 -1.30762150e-02 -8.56047279e-04
  -1.21234099e-04]
 [ 4.76832932e-05 -1.30762150e-02  9.05341934e-04  1.73338529e-05
   1.03814433e-06]
 [-1.01889386e-06 -8.56047279e-04  1.73338529e-05  5.35211609e-06
   4.19638894e-09]
 [-1.10744437e-06 -1.21234099e-04  1.03814433e-06  4.19638894e-09
   1.58047038e-07]]


In [48]:
XtX@XtX_inv

0             1             2             3             4
CRIM  1.000000e+00 -4.447888e-14 -1.020086e-15 -4.691598e-16  2.699273e-18
NOX  -1.452603e-17  1.000000e+00 -2.678151e-16 -2.168159e-18 -3.659899e-18
RM   -9.428389e-17  6.247078e-15  1.000000e+00 -1.370854e-16  3.749752e-18
AGE  -2.786726e-16 -1.250669e-13 -1.535879e-14  1.000000e+00 -7.049449e-17
TAX  -6.501229e-15 -7.405329e-13 -9.465845e-14 -3.369418e-15  1.000000e+00

In [49]:
XtX_inv@XtX

CRIM           NOX            RM           AGE           TAX
0  1.000000e+00 -7.576365e-16 -8.235377e-15 -9.886624e-14 -5.807765e-13
1  1.419495e-13  1.000000e+00  1.941346e-13  2.357091e-12  7.872695e-12
2 -3.420988e-15 -8.161380e-16  1.000000e+00 -9.470352e-14 -3.688790e-13
3 -2.045842e-16 -3.458849e-17 -3.330749e-16  1.000000e+00 -1.846921e-14
4  2.699273e-18 -3.659899e-18  3.749752e-18 -7.049449e-17  1.000000e+00