In [28]:
import numpy as np

In [29]:
input_data = np.array([[2,3], [5,1]])
print(input_data)

[[2 3]
 [5 1]]


In [30]:
x = input_data.reshape(-1)
print(x)

[2 3 5 1]


In [31]:
w1 = np.array([2, 1, -3, 3])
w2 = np.array([1, -3, 1, 3])

In [32]:
b1 = 3
b2 = 3

In [33]:
W = np.array([w1, w2])
print(W)

[[ 2  1 -3  3]
 [ 1 -3  1  3]]


In [34]:
b = np.array([b1, b2])
print(b)

[3 3]


In [35]:
weight_sum = np.dot(W, x) + b
print(weight_sum)

[-2  4]


In [36]:
res = 1/(1+np.exp(-weight_sum))
print(res)

[0.11920292 0.98201379]
