In [6]:
class Country01:
    name = '국가명'
    capital = '수도'
    population = 100

    def introduce(self):
        sentence = '국가 소개 문장입니다.'
        return sentence

In [7]:
ex1 = Country01()

In [8]:
ex1.name

'국가명'

In [9]:
ex1.capital

'수도'

In [10]:
ex1.introduce()

'국가 소개 문장입니다.'

In [12]:
class Country02:
    def __init__(self, name, capital, population):
        self.name = name
        self.capital = capital
        self.population = population
        
    def introduce(self):
        sentence = '국가 소개 문장입니다.'
        return sentence

In [13]:
ex2 = Country02(name='Korea', capital='Seoul', population=5000000)

In [14]:
ex2.name

'Korea'

In [15]:
ex2.capital

'Seoul'

In [16]:
ex2.population

5000000

In [19]:
ex2.introduce()

'국가 소개 문장입니다.'

In [20]:
class Korea01(Country01):
    def __init__(self, name):
        self.name = name

    def explanation(self):
        sentence = '국가 이름은 {} 입니다.'.format(self.name)
        return sentence

In [21]:
ex3 = Korea01(name='한국')

In [22]:
ex3.name

'한국'

In [23]:
ex3.capital

'수도'

In [24]:
ex3.population

100

In [25]:
ex3.introduce()

'국가 소개 문장입니다.'

In [26]:
ex3.explanation()

'국가 이름은 한국 입니다.'

In [28]:
class Korea02(Country01):
    def __init__(self, name):
        self.name = name

    def introduce(self):
        sentence = '국가 이름은 {} 입니다.'.format(self.name)
        return sentence

In [29]:
ex4 = Korea02(name='한국')

In [30]:
ex4.name

'한국'

In [31]:
ex4.capital

'수도'

In [32]:
ex4.population

100

In [33]:
ex4.introduce()

'국가 이름은 한국 입니다.'

In [36]:
class Korea03(Country01):
    def __init__(self, name):
        self.name = name

    def introduce(self):
        res1 = super().introduce()
        res2 = '국가 이름은 {} 입니다.'.format(self.name)
        return res1, res2

In [37]:
ex5 = Korea03(name='한국')

In [38]:
ex5.name

'한국'

In [39]:
ex5.capital

'수도'

In [40]:
ex5.population

100

In [42]:
a1, a2 = ex5.introduce()
print(a1)
print(a2)

국가 소개 문장입니다.
국가 이름은 한국 입니다.


In [43]:
class Korea04(Country01):
    def __init__(self, name):
        self.name = name

    def introduce(self):
        res1 = super(Korea04, self).introduce()
        res2 = '국가 이름은 {} 입니다.'.format(self.name)
        return res1, res2

In [44]:
ex6 = Korea03(name='한국')

In [45]:
ex6.name

'한국'

In [46]:
ex6.capital

'수도'

In [47]:
ex6.population

100

In [49]:
a3, a4 = ex6.introduce()
print(a3)
print(a4)

국가 소개 문장입니다.
국가 이름은 한국 입니다.


In [50]:
import numpy as np
import torch

In [51]:
a1 = np.array([1,2,3,4,5,6])
print(a1)

[1 2 3 4 5 6]


In [52]:
a1.ndim

1

In [53]:
a1.shape

(6,)

In [54]:
a1[0]

1

In [55]:
a1[1]

2

In [56]:
a1[-1]

6

In [57]:
a1[2:5]

array([3, 4, 5])

In [58]:
a1[3:-1]

array([4, 5])

In [60]:
a1[:2]

array([1, 2])

In [61]:
a1[3:]

array([4, 5, 6])

In [70]:
a1_torch = torch.FloatTensor([1,2,3,4,5,6])
print(a1_torch)

tensor([1., 2., 3., 4., 5., 6.])


In [63]:
a1_torch.dim()

1

In [64]:
a1_torch.shape

torch.Size([6])

In [65]:
a1_torch.size()

torch.Size([6])

In [66]:
a1_torch[0]

tensor(1.)

In [67]:
a1_torch[1]

tensor(2.)

In [68]:
a1_torch[-1]

tensor(6.)

In [71]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
a2.ndim

2

In [73]:
a2.shape

(4, 3)

In [74]:
a2_torch = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [75]:
a2_torch

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [76]:
a2_torch.dim()

2

In [78]:
a2_torch.size()

torch.Size([4, 3])

In [79]:
a2_torch[:,-1]

tensor([ 3.,  6.,  9., 12.])

In [80]:
a2_torch[:,1].size()

torch.Size([4])

In [81]:
a2_torch[:,:-1]

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [82]:
a3 = torch.FloatTensor([1,2])
print(a3)

tensor([1., 2.])


In [83]:
a3.dim()

1

In [84]:
a3.size()

torch.Size([2])

In [85]:
a4 = torch.FloatTensor([[1,2]])
print(a4)

tensor([[1., 2.]])


In [86]:
a4.dim()

2

In [87]:
a4.size()

torch.Size([1, 2])

In [88]:
v1 = torch.FloatTensor([[3,3]])

In [89]:
v1

tensor([[3., 3.]])

In [90]:
v2 = torch.FloatTensor([5,5])

In [91]:
v2

tensor([5., 5.])

In [92]:
v1 + v2

tensor([[8., 8.]])

In [94]:
v3 = torch.FloatTensor([[1,2]])
v4 = torch.FloatTensor([3])

In [95]:
v3 + v4

tensor([[4., 5.]])

In [96]:
v5 = torch.FloatTensor([[1,2]])
v6 = torch.FloatTensor([[3], [4]])

In [97]:
v5 + v6

tensor([[4., 5.],
        [5., 6.]])

In [98]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[5], [6]])

In [99]:
m1.matmul(m2)

tensor([[17.],
        [39.]])

In [100]:
m3 = torch.FloatTensor([[1,2], [3,4]])
m4 = torch.FloatTensor([[5], [6]])

In [101]:
m3 * m4

tensor([[ 5., 10.],
        [18., 24.]])

In [102]:
m3.mul(m4)

tensor([[ 5., 10.],
        [18., 24.]])

In [103]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])

In [104]:
m1.mean()

tensor(2.5000)

In [105]:
m1.mean(dim=0)

tensor([2., 3.])

In [107]:
m1.mean(dim=1)

tensor([1.5000, 3.5000])

In [108]:
m1.mean(dim=-1)

tensor([1.5000, 3.5000])

In [109]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])

In [110]:
m1.sum()

tensor(10.)

In [111]:
m1.sum(dim=0)

tensor([4., 6.])

In [112]:
m1.sum(dim=1)

tensor([3., 7.])

In [113]:
m1.sum(dim=-1)

tensor([3., 7.])

In [114]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])

In [115]:
m1.max()

tensor(4.)

In [116]:
m1.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [117]:
print('max = ', m1.max(dim=0)[0])

max =  tensor([3., 4.])


In [118]:
print('argmax = ', m1.max(dim=0)[1])

argmax =  tensor([1, 1])


In [119]:
m1.max(dim=1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

In [120]:
print('max = ', m1.max(dim=1)[0])

max =  tensor([2., 4.])


In [121]:
print('argmax = ', m1.max(dim=1)[1])

argmax =  tensor([1, 1])


In [122]:
m1.min()

tensor(1.)

In [123]:
m1.min(dim=1)

torch.return_types.min(
values=tensor([1., 3.]),
indices=tensor([0, 0]))

In [124]:
m1.min(dim=0)

torch.return_types.min(
values=tensor([1., 2.]),
indices=tensor([0, 0]))

In [130]:
t = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [131]:
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 3, 4])


In [132]:
ft.size()

torch.Size([2, 3, 4])

In [133]:
ft.view([-1, 3])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])

In [134]:
ft.view([-1, 3]).shape

torch.Size([8, 3])

In [135]:
ft.view([-1, 1, 3])

tensor([[[ 1.,  2.,  3.]],

        [[ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.]],

        [[10., 11., 12.]],

        [[13., 14., 15.]],

        [[16., 17., 18.]],

        [[19., 20., 21.]],

        [[22., 23., 24.]]])

In [136]:
ft.view([-1, 1, 3]).shape

torch.Size([8, 1, 3])

In [137]:
ft = torch.FloatTensor([[0], [1], [2]])

In [138]:
ft

tensor([[0.],
        [1.],
        [2.]])

In [139]:
ft.shape

torch.Size([3, 1])

In [140]:
ft.squeeze()

tensor([0., 1., 2.])

In [141]:
ft.squeeze().shape

torch.Size([3])

In [143]:
ft = torch.Tensor([1, 2, 3])
print(ft)
print(ft.shape)

tensor([1., 2., 3.])
torch.Size([3])


In [144]:
ft.unsqueeze(0)

tensor([[1., 2., 3.]])

In [145]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [147]:
ft.view(1, -1)

tensor([[1., 2., 3.]])

In [148]:
ft.view(1, -1).shape

torch.Size([1, 3])

In [149]:
ft.unsqueeze(1)

tensor([[1.],
        [2.],
        [3.]])

In [150]:
ft.unsqueeze(1).shape

torch.Size([3, 1])

In [151]:
ft.unsqueeze(-1)

tensor([[1.],
        [2.],
        [3.]])

In [152]:
ft.unsqueeze(-1).shape

torch.Size([3, 1])

In [153]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [154]:
lt.float()

tensor([1., 2., 3., 4.])

In [155]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [156]:
bt.long()

tensor([1, 0, 0, 1])

In [157]:
bt.float()

tensor([1., 0., 0., 1.])

In [158]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [159]:
torch.cat([x, y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [160]:
torch.cat([x, y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [161]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [162]:
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [163]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [164]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [165]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [166]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [167]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [169]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [170]:
x

tensor([[1., 2.],
        [3., 4.]])

In [171]:
x.mul_(2)

tensor([[2., 4.],
        [6., 8.]])

In [172]:
x

tensor([[2., 4.],
        [6., 8.]])